// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tooltip-window': string;
  'tooltip-window__arrow': string;
  'tooltip-window__arrow_dark': string;
  'tooltip-window__arrow_visible': string;
  'tooltip-window_active': string;
  'tooltip-window_dark': string;
}
export const cssExports: CssExports;
export default cssExports;
