// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'clip-left': string;
  'clip-right': string;
  'dark': string;
  'left': string;
  'light': string;
  'right': string;
  'tooltip': string;
  'tooltip__arrow': string;
  'tooltip__body': string;
  'tooltip__trigger': string;
  'tooltip_active': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
