// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'brick': string;
  'btn': string;
  'clear': string;
  'clip': string;
  'danger': string;
  'full-size': string;
  'l': string;
  'loading': string;
  'm': string;
  'primary': string;
  'round': string;
  's': string;
  'success': string;
  'xs': string;
}
export const cssExports: CssExports;
export default cssExports;
